// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdlawtmctpogbtjhtzse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbGF3dG1jdHBvZ2J0amh0enNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDIyODgsImV4cCI6MjA2NDgxODI4OH0.n4TdTH_TaQp5gUJy4V-VOk2yuRl-84oiCM3Q4kLyyaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);